### ISSUE TITLE
Checksums missing in ControlUnit.press() and .reset()

### ISSUE THREAD

**Issue by grosssoftware** [tkem/carreralib#15]
Per [Slotbaer's documentation](http://slotbaer.de/carrera-digital-124-132/10-cu-rundenzaehler-protokoll.html), the reset command `=` and the button press command `T` should transmit the checksum. Note that in the documentation for reset, the full command is `"=101$` where the last `1` plays the role of checksum.

**Comment by grosssoftware** [comment]
```
diff --git a/src/carreralib/cu.py b/src/carreralib/cu.py
index e744f16..4bd3aa4 100644
--- a/src/carreralib/cu.py
+++ b/src/carreralib/cu.py
@@ -132,7 +132,7 @@ class ControlUnit(object):
 
     def press(self, button_id):
         """Simulate pressing the CU button with the given ID."""
-        return self.request(protocol.pack("cY", b"T", button_id))
+        return self.request(protocol.pack("cYC", b"T", button_id))
 
     def request(self, buf, maxlength=None):
         """Send a message to the CU and wait for a response."""
@@ -152,7 +152,7 @@ class ControlUnit(object):
 
     def reset(self):
         """Reset the CU timer."""
-        self.request(b"=10")
+        self.request(protocol.pack('cYYC', b'=', 1, 0))
 
     def setbrake(self, address, value):
         """Set the brake value for controller `address`."""
```

**Comment by grosssoftware** [comment]
If you'd like to elevate my access, I'd be happy to help out where I can and push fixes to branches. Let me know!

**Comment by tkem** [comment]
@grosssoftware: `carreralib` predates the Slotbaer documentation, and apparently the commands work without the checksum or the last `1`, but I agree, for the sake of consistency this should be changed. Just have to check this works with BLE/AppConnect, too.

**Comment by tkem** [comment]
There currently seems to be an issue with flake8 in GitHub Actions - nothing you should worry about, but I think I'll wait until this gets resolved, anyway. So please be patient ;-)

**Comment by tkem** [comment]
Thanks for your contributions, these are very much appreciated!
Regarding elevating your access - maybe not for now says my inner control freak, but after v1.0.0 gets released, we'll see ;-)

**Comment by grosssoftware** [comment]
No worries! I will continue to contribute via PR from my fork as necessary. Thanks for incorporating my changes!

**Comment by tkem** [comment]
No, thank _you_! It feels good to have some contributions after all these years ;-)
