### ISSUE TITLE
Fuel always 0...

### ISSUE THREAD

**Issue by detbetteegern** [tkem/carreralib#2]
Sorry, don't know if this is the right way to contact you, but I've not been able to find any other...

I've been trying to create my own RaceControl app using carreralab 0.4.1 - and I've noticed that the status line returned from cu.request() always has fuel=0 for all drivers:
[2017-05-08 17:37:11,383] dk.fafdifh.racecontrol.config.RaceControl.getStatus(RaceControl.java:86) [INFO] [pool-1-thread-1] status : Status(fuel=(0, 0, 0, 0, 0, 0, 0, 0), start=0, mode=2, pit=(False, False, False, False, False, False, False, False), display=8)

This is also the case when I use the RMS demo inside carreralib directly.

I've tried both the Fuel=On and Fuel=Real setting on my (physical) CU to no avail. Am I doing something wrong? All the demo screenshots present various % fuel...

**Comment by tkem** [comment]
Yes, it is the right way ;-)
Do you have the Carrera Pit Lane installed on your track?
Without a pit lane attached, the Control Unit will always report 0 for fuel, no matter what you set your fuel mode to!

**Comment by tkem** [comment]
Well, apparently you don't, because otherwise your `mode` would be 4 or greater (flag for pit lane detected) ;-)

**Comment by detbetteegern** [comment]
Jeez, is that it!? No, I don't have a pitlane. I only have a very small track setup to test with.

But I'll add the pitlane and see if that helps.

Thanks a lot!

**Comment by tkem** [comment]
Yes, I've got bitten myself a couple of times when I only had a small test setup. However, it does make some sense - what use is fuel mode if you cannot refuel?

**Comment by detbetteegern** [comment]
You're right of course :) And adding the pit lane did the trick.

Just one other question. When I execute cu.request() I get back either a Timer or a Status. But I cannot figure out when I get what. I have one car circling the track and I first thought that the Timer came every time I crossed the finish line. But that does not seem to be so...?

**Comment by tkem** [comment]
Should work the way you expected. Buffering on the CU side may get in the way, so you receive Timer a little (one or two requests) later.

**Comment by tkem** [comment]
And be sure to "poll" the CU as often as you can...

**Comment by detbetteegern** [comment]
Aah, figured it out - I need to continue making cu.request() calls until the same value is returned twice. Then I can sleep :)

Thanks!

**Comment by detbetteegern** [comment]
I have a couple of questions if you don't mind. 
I'm pretty far along with my race app, but there is something I don't understand.

There is no position or lap information in the status messages sent by the CU, only lap times, fuel status and pit status. So what are these methods in the interface used for?

clrpos()
setlap(value)
setlap_hi(value)
setlap_lo(value)
setpos(address, position)

**Comment by tkem** [comment]
These are used for controlling the Carrera [Position Tower](http://www.carrera-toys.com/de/sortiment/digital-132/zubehoer/position-tower-365/) or similar equipment.

**Comment by detbetteegern** [comment]
Aah, of course. Haven't got one of those :)

What's the difference between setlap and setlap_hi/lo

**Comment by tkem** [comment]
setlap() takes an 8-bit number (though only 0..250 can be displayed by the position tower), while setlap_hi/lo take 4-bit numbers, the high/low "nibble" of the lap. Could - in theory - be used for efficiency, i.e. save one command to the CU, but things get just too low-level here...

**Comment by detbetteegern** [comment]
Okay, thanks for all your (speedy) help :+1:

**Comment by tkem** [comment]
Unless you have any further questions, I think we can close this, or can't we?

**Comment by tkem** [comment]
And if you want to share any details about your project - I'm curious ;-)

**Comment by detbetteegern** [comment]
You can close this indeed, I'm happy :+1: 

I'm just creating a raceapp for myself. The one Carrera is offering is simply terrible, so I thought "I can do better" :)
