### ISSUE TITLE
Support for Go!+ ?

### ISSUE THREAD

**Issue by alexfederlin** [tkem/carreralib#8]
Hi! Do you have any intentions or plans to make this lib compatible to the Carrera Go! + Controller?
From the limited research I did using a Bluetooth Terminal app, the protocol is quite similar for the basic stuff (i.e. getting lap times)
However, when I try to connect to it using this version of carreralib, I get a timeout while trying to get the CU version on program launch. I tried to increase the timeout to 5 seconds to no avail.

**Comment by tkem** [comment]
@alexfederlin Since I do not own a Go!!! Plus, there are no plans for supporting it, nor can I do any testing with that system.
From what I've heard, the protocols are indeed very similar, but I don't know any details.

**Comment by alexfederlin** [comment]
Ok, thanks for the feedback.
